import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Rubik } from "next/font/google";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import { Breadcrumb } from "@/components/ui/breadcrumb";
import AddClientButton from "../components/(Bookings)/AddClientButton/page";
import { usePathname } from "next/navigation";
import Provider from "@/components/Providers/tanstack-provider";
import Header from "@/components/modules/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={"font-roboto antialiased"}>
        <div className="top-0 sticky bg-white z-90 overflow-x-hidden shadow-md shadow-neutral-200/40">
          <Header />
        </div>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
