import { ConditionalLayout } from "@/components/conditional-layout";
import Provider from "@/components/Providers/tanstack-provider";
import { BookingSystemProvider } from "@/components/BookingSystemProvider";
import { BookingSync } from "@/components/BookingSync";
import { ScheduledNotificationProcessor } from "@/components/ScheduledNotificationProcessor";
import { BookingStatusInitializer } from "@/components/BookingStatusInitializer";
import type { Metadata } from "next";
import { Geist, Rubik, Rufina } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const rufina = Rufina({
  variable: "--font-rufina",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${rufina.variable} font-roboto antialiased`}>
        <Provider>
          <BookingSystemProvider
            statusUpdateInterval={5000}
            notificationCheckInterval={10000}
            enableStatusUpdates={true}
            enableNotifications={true}
            showToasts={false}
          >
            <BookingSync />
            <ScheduledNotificationProcessor />
            <BookingStatusInitializer />
            <ConditionalLayout>{children}</ConditionalLayout>
          </BookingSystemProvider>
        </Provider>
      </body>
    </html>
  );
}
