"use client";

import { ColumnDef } from "@tanstack/react-table";
import { Checkbox } from "@/components/ui/checkbox";
import { formatDistanceToNow } from "date-fns";
import { Badge } from "@/components/ui/badge";

export type SavedReport = {
  id: string;
  name: string;
  reportType: string;
  parameters: string;
  reportData: string;
  generatedBy: string | null;
  createdAt: Date | string;
};

export const columns: ColumnDef<SavedReport>[] = [
  {
    id: "select",
    header: ({ table }) => (
      <Checkbox
        checked={
          table.getIsAllPageRowsSelected() || (table.getIsSomePageRowsSelected() && "indeterminate")
        }
        onCheckedChange={value => table.toggleAllPageRowsSelected(!!value)}
        aria-label="Select all"
      />
    ),
    cell: ({ row }) => (
      <Checkbox
        checked={row.getIsSelected()}
        onCheckedChange={value => row.toggleSelected(!!value)}
        aria-label="Select row"
        onClick={e => e.stopPropagation()}
      />
    ),
    enableSorting: false,
    enableHiding: false,
  },
  {
    accessorKey: "name",
    header: "Report Name",
    cell: ({ row }) => {
      return <div className="font-medium">{row.getValue("name")}</div>;
    },
  },
  {
    accessorKey: "reportType",
    header: "Report Type",
    cell: ({ row }) => {
      const type = row.getValue("reportType") as string;
      return (
        <Badge variant="secondary" className="capitalize">
          {type.replace(/_/g, " ")}
        </Badge>
      );
    },
  },
  {
    accessorKey: "createdAt",
    header: "Generated",
    cell: ({ row }) => {
      const date = row.getValue("createdAt");
      return (
        <div className="text-sm text-muted-foreground">
          {formatDistanceToNow(new Date(date as string), { addSuffix: true })}
        </div>
      );
    },
  },
  {
    accessorKey: "generatedBy",
    header: "Generated By",
    cell: ({ row }) => {
      const generatedBy = row.getValue("generatedBy") as string | null;
      return (
        <div className="text-sm">
          {generatedBy || <span className="text-muted-foreground">System</span>}
        </div>
      );
    },
  },
];
